### ISSUE TITLE
[バグ]ページ初期読み込み時に、一瞬メニューがちらつく現象

### ISSUE THREAD

**Issue by h-yoshikawa44** [h-yoshikawa44/ch-interior-consultant#11]
## 期待する動作
ページ初期読み込み時に、メニューがちらつかない

## 不具合内容
![menu-bug](https://user-images.githubusercontent.com/43331308/144552086-b98952bd-5c36-4a6d-9ca5-12bf045b5143.gif)

ページ初期読み込み時に、一瞬メニューがちらついてしまう

## 再現方法
Chrome でページを表示して再読み込みを実行

**Comment by h-yoshikawa44** [comment]
## 原因調査
調べた中で一番近い感じがしたのがこちら
- [Chrome の CSS transition がページロード時に動いてしまう問題の機序と対処](https://qiita.com/nagtkk/items/27ff4f2fe17746afabdd)

メニュー本体のスタイル
```css
.menu {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1200;
  width: 100%;
  height: 100%;
  overflow-y: auto;
  visibility: hidden;
  background-color: var(--bg-color);
  opacity: 0%;
  transition: opacity 0.3s, visibility 0.3s ease 0.3s, transform 0.3s;
  transform: translateX(100%);
}
```

記事によれば回避策として、なにかしらスクリプトを読み込めばいいとある。
今回の場合、Vite でのモジュール読み込みが body の末尾にあるのだが発生しているので、この方法はダメっぽい。
```html
<script type="module" src="/js/main.js"></script>
```

**Comment by h-yoshikawa44** [comment]
## 現象回避
上記コメントの参考記事に記載のあった、こちらの記事のやり方を試してみたところ、発生しないようにできた。
- [Transitions Only After Page Load](https://css-tricks.com/transitions-only-after-page-load/)

body にクラス追加
```html
<body class="js-preload">
  ...
</body>
```

transition を無効化するスタイル追記
```css
/* load */
.js-preload * {
  transition: none !important;
}
```

JS で、ページ読み込み後はそのクラスを除去するようにイベント追加
```js
window.addEventListener('load', () => {
  document
    .getElementsByClassName('js-preload')[0]
    .classList.remove('js-preload');
});
```

一工夫必要なのが気になるところであるが、今のところこれくらいしか通用した対処法がないのでしょうがない。
